In [1]:
import numpy as np

# Funciones Universales

### Caracteristicas
- Presentan Broadcasting: Convenciones internas de Numpypara aplicar operaciones entre filas, columnas y matrices
- Especializadas con código vectorizado (rápido y eficiente)
- Funciones Puras, mismo valor si ingresamos el mismo input
- Otros aspectos como type casting, argumentos utiles, etc

# Broadcasting entre filas

In [10]:
arr1 = np.linspace(0, 75).round(2)
arr1

array([ 0.  ,  1.53,  3.06,  4.59,  6.12,  7.65,  9.18, 10.71, 12.24,
       13.78, 15.31, 16.84, 18.37, 19.9 , 21.43, 22.96, 24.49, 26.02,
       27.55, 29.08, 30.61, 32.14, 33.67, 35.2 , 36.73, 38.27, 39.8 ,
       41.33, 42.86, 44.39, 45.92, 47.45, 48.98, 50.51, 52.04, 53.57,
       55.1 , 56.63, 58.16, 59.69, 61.22, 62.76, 64.29, 65.82, 67.35,
       68.88, 70.41, 71.94, 73.47, 75.  ])

In [21]:
arr2 = np.linspace(0, 50).round(2)
arr2

array([ 0.  ,  1.02,  2.04,  3.06,  4.08,  5.1 ,  6.12,  7.14,  8.16,
        9.18, 10.2 , 11.22, 12.24, 13.27, 14.29, 15.31, 16.33, 17.35,
       18.37, 19.39, 20.41, 21.43, 22.45, 23.47, 24.49, 25.51, 26.53,
       27.55, 28.57, 29.59, 30.61, 31.63, 32.65, 33.67, 34.69, 35.71,
       36.73, 37.76, 38.78, 39.8 , 40.82, 41.84, 42.86, 43.88, 44.9 ,
       45.92, 46.94, 47.96, 48.98, 50.  ])

In [23]:
arr1 * arr2 # esto llama la funcion universal

array([0.0000000e+00, 1.5606000e+00, 6.2424000e+00, 1.4045400e+01,
       2.4969600e+01, 3.9015000e+01, 5.6181600e+01, 7.6469400e+01,
       9.9878400e+01, 1.2650040e+02, 1.5616200e+02, 1.8894480e+02,
       2.2484880e+02, 2.6407300e+02, 3.0623470e+02, 3.5151760e+02,
       3.9992170e+02, 4.5144700e+02, 5.0609350e+02, 5.6386120e+02,
       6.2475010e+02, 6.8876020e+02, 7.5589150e+02, 8.2614400e+02,
       8.9951770e+02, 9.7626770e+02, 1.0558940e+03, 1.1386415e+03,
       1.2245102e+03, 1.3135001e+03, 1.4056112e+03, 1.5008435e+03,
       1.5991970e+03, 1.7006717e+03, 1.8052676e+03, 1.9129847e+03,
       2.0238230e+03, 2.1383488e+03, 2.2554448e+03, 2.3756620e+03,
       2.4990004e+03, 2.6258784e+03, 2.7554694e+03, 2.8881816e+03,
       3.0240150e+03, 3.1629696e+03, 3.3050454e+03, 3.4502424e+03,
       3.5985606e+03, 3.7500000e+03])

### np.multiply()

In [26]:
np.multiply(arr1, arr2)
# Broadcasting entre vectores, realiza la operación entre elementos de las mismas posiciones

array([0.0000000e+00, 1.5606000e+00, 6.2424000e+00, 1.4045400e+01,
       2.4969600e+01, 3.9015000e+01, 5.6181600e+01, 7.6469400e+01,
       9.9878400e+01, 1.2650040e+02, 1.5616200e+02, 1.8894480e+02,
       2.2484880e+02, 2.6407300e+02, 3.0623470e+02, 3.5151760e+02,
       3.9992170e+02, 4.5144700e+02, 5.0609350e+02, 5.6386120e+02,
       6.2475010e+02, 6.8876020e+02, 7.5589150e+02, 8.2614400e+02,
       8.9951770e+02, 9.7626770e+02, 1.0558940e+03, 1.1386415e+03,
       1.2245102e+03, 1.3135001e+03, 1.4056112e+03, 1.5008435e+03,
       1.5991970e+03, 1.7006717e+03, 1.8052676e+03, 1.9129847e+03,
       2.0238230e+03, 2.1383488e+03, 2.2554448e+03, 2.3756620e+03,
       2.4990004e+03, 2.6258784e+03, 2.7554694e+03, 2.8881816e+03,
       3.0240150e+03, 3.1629696e+03, 3.3050454e+03, 3.4502424e+03,
       3.5985606e+03, 3.7500000e+03])

### Broadcast entre columnas
```python
np.subtract(a, b)
```

In [40]:
arr3 = arr1.copy().reshape(50, 1)
arr4 = arr2.copy().reshape(50, 1)
np.subtract(arr3, arr4) # existe la correspondencia elemento por elemento respetando las mismas posiciones
# cuando se suministran dos columnas o mas este broadcasting no funciona igual, por eso se hizo sobre una columna

array([[ 0.  ],
       [ 0.51],
       [ 1.02],
       [ 1.53],
       [ 2.04],
       [ 2.55],
       [ 3.06],
       [ 3.57],
       [ 4.08],
       [ 4.6 ],
       [ 5.11],
       [ 5.62],
       [ 6.13],
       [ 6.63],
       [ 7.14],
       [ 7.65],
       [ 8.16],
       [ 8.67],
       [ 9.18],
       [ 9.69],
       [10.2 ],
       [10.71],
       [11.22],
       [11.73],
       [12.24],
       [12.76],
       [13.27],
       [13.78],
       [14.29],
       [14.8 ],
       [15.31],
       [15.82],
       [16.33],
       [16.84],
       [17.35],
       [17.86],
       [18.37],
       [18.87],
       [19.38],
       [19.89],
       [20.4 ],
       [20.92],
       [21.43],
       [21.94],
       [22.45],
       [22.96],
       [23.47],
       [23.98],
       [24.49],
       [25.  ]])

## Broadcast entre filas y columnas
````python
np.logaddexp()
```

In [41]:
np.logaddexp(arr1, arr3)

array([[ 0.69314718,  1.7260072 ,  3.10582166, ..., 71.94      ,
        73.47      , 75.        ],
       [ 1.7260072 ,  2.22314718,  3.2560072 , ..., 71.94      ,
        73.47      , 75.        ],
       [ 3.10582166,  3.2560072 ,  3.75314718, ..., 71.94      ,
        73.47      , 75.        ],
       ...,
       [71.94      , 71.94      , 71.94      , ..., 72.63314718,
        73.6660072 , 75.04582166],
       [73.47      , 73.47      , 73.47      , ..., 73.6660072 ,
        74.16314718, 75.1960072 ],
       [75.        , 75.        , 75.        , ..., 75.04582166,
        75.1960072 , 75.69314718]])

In [42]:
np.logaddexp(arr1, arr3).shape

(50, 50)

NOTA: 
El broadcast entre filas y columnas NO es lo mismo que la multiplicación de matrices, en donde la forma de las matrices juegan un papel necesario para la aplicación de las mismas así como de su resultado.