In [1]:
import numpy as np

## Determinante de una Matriz

In [9]:
arr = np.arange(0, 9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

1. Calculamos el producto de las primera diagonal

In [12]:
d1 = arr[[0,1,2],[0,1,2]].prod()
d1

0

2. Trasladamos las primeras columnas una posición adelante

In [14]:
np.roll(arr, -1, axis=1) # Columa 1 ahora es 0 y columna 2 ahora es 1

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

In [22]:
d2 = np.roll(arr, -1, axis=1) [[0,1,2],[0,1,2]].prod()
d2

30

In [17]:
np.roll(arr, -2, axis=1)

array([[2, 0, 1],
       [5, 3, 4],
       [8, 6, 7]])

In [18]:
d3 = np.roll(arr, -2, axis=1) [[0,1,2],[0,1,2]].prod()
d3

42

In [25]:
dn1 = arr[[2,1,0],[0,1,2]].prod()
dn1

48

In [26]:
dn2 = np.roll(arr, -1, axis=1) [[2,1,0],[0,1,2]].prod()
dn2

0

In [27]:
dn3 = np.roll(arr, -2, axis=1) [[2,1,0],[0,1,2]].prod()
dn3

24

In [29]:
det = d1 + d2 +d3 - (dn1 + dn2 + dn3)
det

0

In [30]:
# Usando la funcionalidad de Numpy
np.linalg.det(arr)

0.0