In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\hernveor\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

### Un array tiene ttres componentes fundamentales:
1. El array propiamente
2. El objeto de tipo de datos
3. El tipo de Escalar

### Diferencia entre np.array(...) y np.ndarray(...)

El método np.array(...) es el más utilizado comúnmente para crear arrays por construcción. Es el método recomendado por numpy oficial.

Sin embargo, también existe el método np.ndarray(...), el cual es un método más de bajo nivel y más programático. De hecho, numpy.ndarray es la clase (tipo) del cual derivan todos los objetos de arrays.

En otras palabras, en python prueba esto:
```python
isinstance(np.array([...]), np.ndarray)    # ===> True
```

lo cual significa que todo np.array(...) es una instancia derivada de la clase de np.ndarray(...), con todos sus atributos y métodos predeterminados.

Así las cosas, np.ndarray(...) es más de bajo nivel programático, pero para efectos prácticos, crear matrices con np.array(...) es la forma recomendada (más las otras formas que veremos más adelante)>

In [3]:
# Crear un array
np.array(1)

array(1)

In [6]:
miArray2 = np.array(list([1,2,3,4,5]))

In [7]:
miArray2

array([1, 2, 3, 4, 5])

In [8]:
miArray3 = np.array([1,2,3,4,5])

In [9]:
miArray3

array([1, 2, 3, 4, 5])

In [13]:
# matriz 2x2
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [14]:
# matriz 3x3
miMatriz3x3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [15]:
miMatriz3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array con Valores Aleatorios
```python
np.random.randint()
```

In [35]:
aleatorio = np.random.randint(11, 20, 50)
aleatorio2 = np.random.random(50)

In [36]:
aleatorio

array([19, 14, 19, 19, 18, 14, 18, 14, 11, 15, 18, 11, 16, 13, 18, 17, 12,
       12, 15, 15, 13, 14, 19, 16, 19, 13, 13, 15, 13, 16, 12, 14, 12, 13,
       16, 14, 17, 17, 16, 13, 18, 18, 12, 15, 16, 13, 18, 13, 12, 15])

In [37]:
aleatorio2

array([0.05895056, 0.1537384 , 0.83964293, 0.18414411, 0.41219348,
       0.33702869, 0.25446505, 0.63635377, 0.5607668 , 0.92010735,
       0.74276338, 0.26819643, 0.24792611, 0.56460685, 0.35410724,
       0.86647049, 0.66583959, 0.33924103, 0.16949843, 0.34315659,
       0.54065787, 0.67857696, 0.24272001, 0.51286457, 0.8172537 ,
       0.96477803, 0.79680361, 0.01313992, 0.21780068, 0.50032994,
       0.94748529, 0.23016235, 0.99115947, 0.07338855, 0.41874324,
       0.17177117, 0.5451382 , 0.32278078, 0.68722877, 0.87562222,
       0.20707174, 0.89283676, 0.51621007, 0.68496591, 0.43100067,
       0.08746835, 0.66085616, 0.34081118, 0.24205786, 0.3468933 ])