In [1]:
import numpy as np

## Iteración más fácil con np.nditer()

In [2]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.nditer(arr)

In [4]:
arr = np.arange(0,16).reshape(2,2,2,2) # cuatro dimenciones
arr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [6]:
for i in np.nditer(arr): # recogge elemento a elemento
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


##  Controlando el Orden

In [7]:
arr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [11]:
for i in np.nditer(arr, order="C"): # es el orden por defecto
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [12]:
for i in np.nditer(arr, order="F"): # primero las primeras posiciones de todos los elementos
    print(i)

0
8
4
12
2
10
6
14
1
9
5
13
3
11
7
15


In [13]:
for i in np.nditer(arr, order="A"): # igual a A?
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [15]:
for i in np.nditer(arr, order="K"): # tambien igual a A y C?
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
