In [1]:
import numpy as np

## Funciones Lógicas

In [2]:
mat = np. random.randint(-5, 5, (4, 4))
mat

array([[ 3,  4,  0, -4],
       [ 4, -2,  4, -1],
       [-5, -5,  4, -2],
       [-3, -1,  4,  0]])

In [4]:
vec = np.random.randint(1, 4, (1, 4))
vec

array([[3, 1, 1, 1]])

### np.greater()
Es mayor que, uno por uno

In [7]:
np.greater(mat, mat)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [8]:
np.greater(mat, vec)

array([[False,  True, False, False],
       [ True, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False]])

### np.not_equal()
son diferentes

In [9]:
np.not_equal(mat, vec)

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### np.logical_and()
- Solo retorna True cuando ambos True.
- en numeros solo es False cuando es 0

In [10]:
np.logical_and(mat, vec)

array([[ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [11]:
mat, vec

(array([[ 3,  4,  0, -4],
        [ 4, -2,  4, -1],
        [-5, -5,  4, -2],
        [-3, -1,  4,  0]]), array([[3, 1, 1, 1]]))

### np.logical_or
- Retorna True cuando existe almenos un True
- Solo el cero retorna False

In [13]:
np.logical_or(mat, vec)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### np.logical_not()
- Negación lógica

In [14]:
np.logical_not(mat)

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

### np.maximun()
- numero mayor elemento a elemento

In [15]:
np.maximum(mat, vec)

array([[3, 4, 1, 1],
       [4, 1, 4, 1],
       [3, 1, 4, 1],
       [3, 1, 4, 1]])

In [16]:
np.minimum(mat, vec)

array([[ 3,  1,  0, -4],
       [ 3, -2,  1, -1],
       [-5, -5,  1, -2],
       [-3, -1,  1,  0]])

### Nota:

- No se recomienda usar and o or de Python con matrices de Numpy porque esos realizarán la comparación sobre toda la matriz, en cambio las funciones universales de logical_and() y logical_or() sí realizan la comparación elemento por elemento dentro de cada matriz.

- Esto significa, naturalmente, que las funciones unversales de numpy tienen mayor flexibilidad y aplicación para las matrices que los métodos primitivos de Python.