In [1]:
import numpy as np

## Iteración Simple

In [2]:
arr = np.arange(0,8).reshape(2,2,2)
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [3]:
#ejemplo sencillo
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


### Matriz de una dimensión

In [4]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [5]:
# para un array unidimensional
for val in arr:
    print(val)

0
1
2
3
4


### Matriz de dos dimensiones

In [6]:
arr2 = np.arange(0,6).reshape(2,3)
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
for val in arr2: # solo se accede a los elementos de mas alto nivel de la matriz, no a los subelementos
    print(val)

[0 1 2]
[3 4 5]


In [9]:
for val in arr2: # solo se accede a los elementos de mas alto nivel de la matriz, no a los subelementos
    for item in val: # accedemos al subelemento
        print(item)

0
1
2
3
4
5


### Matriz de tres dimensiones

In [10]:
arr3 = np.arange(0,16).reshape(2,2,4)
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [11]:
for mat in arr3:
    print(mat)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [12]:
for mat in arr3:
    for vec in mat:
        print(vec)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [13]:
for mat in arr3:
    for vec in mat:
        for item in vec:
            print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


Nota:
En la lección anterior, si te quedaron dudas acerca de por qué algunos objetos permiten ser "iterables", es posible si tiene definido el método de iter.

Para saber esto, simplemente ejecuta el dir() de algún objeto, y busca si de verdad lo tiene.

palabra = 'perro'

dir(palabra)

¿Aparece el método de iter() ?

In [14]:
p = 'Perro'
dir(p)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
