In [1]:
import numpy as np

## Indexación Avanzada: Selección Booleana
Utiliza expresiones booleanas como parte de la indexación

In [3]:
arr = np.arange(0,16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
arr >5 # Evalua elemento a elemento la expresión booleana

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [6]:
arr != 5

array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [8]:
(arr > 5)  & (arr < 10)

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [10]:
(arr > 5)  | (arr < 10)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [11]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
arr2 = arr[arr>5]# se pierde la forma, al ser una cantidad diferente
arr2

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
arr3 =arr[(arr > 5)  & (arr < 10)]
arr3

array([6, 7, 8, 9])