In [1]:
import numpy as np

In [2]:
A = np.array([[1, -3],[4, -2]])
A

array([[ 1, -3],
       [ 4, -2]])

In [3]:
b = np.array([6, -3])
b

array([ 6, -3])

In [6]:
# Aplicamos la regla de Cramer
# primero para x1
# Seria calcular D1, D y luego hacer la división

In [7]:
D1 = A.copy()
D1

array([[ 1, -3],
       [ 4, -2]])

In [8]:
# Ahora sustituyo la primera columna con b, eso seria B1

In [10]:
D1[:, 0] = b
D1

array([[ 6, -3],
       [-3, -2]])

In [11]:
# Ahora averigüo x1 primero
D1_det = D1[0, 0] * D1[1, 1] - D1[0, 1] * D1[1, 0]
D1_det

-21

In [14]:
D_det = A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0]
D_det

10

In [16]:
x1 = D1_det / D_det
x1

-2.1

In [17]:
# AHora lo mismo para x2

In [21]:
D2 = A.copy()
D2

array([[ 1, -3],
       [ 4, -2]])

In [22]:
D2[:, 1] = b
D2

array([[ 1,  6],
       [ 4, -3]])

In [27]:
x2 = (D2[0, 0] * D2[1, 1] - D2[0, 1] * D2[1, 0]) / D_det
x2

-2.7

In [29]:
# Prueba, debe dar 6 para la primera fila
(A[0, :] * np.array([x1, x2])).sum()

6.000000000000002

In [30]:
# Prueba, debe dar .3 para la segunda fila
(A[1, :] * np.array([x1, x2])).sum()

-3.0