In [1]:
import numpy as np

## Funciones Universales: Gran Variedad

In [4]:
mat = np.random.randint(-5 ,5, (4,4))
mat

array([[ 2,  3, -2,  2],
       [-3, -5,  2,  0],
       [-5, -1, -2, -2],
       [ 2,  2,  2, -5]])

In [6]:
vet = np.random.randint(-5 ,5, (1,4))
vet

array([[ 1, -2, -1,  2]])

In [7]:
np.add(mat, mat) # suma elemento por elemento

array([[  4,   6,  -4,   4],
       [ -6, -10,   4,   0],
       [-10,  -2,  -4,  -4],
       [  4,   4,   4, -10]])

In [8]:
mat + mat # mismo resultaso

array([[  4,   6,  -4,   4],
       [ -6, -10,   4,   0],
       [-10,  -2,  -4,  -4],
       [  4,   4,   4, -10]])

In [11]:
np.subtract(mat, mat) # debo tener solo ceros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.subtract(mat, np.abs(mat)) # resta de la matriz cons los valores absolutos de la misma matriz

array([[  0,   0,  -4,   0],
       [ -6, -10,   0,   0],
       [-10,  -2,  -4,  -4],
       [  0,   0,   0, -10]])

In [14]:
# valor absoluto
np.abs(mat)

array([[2, 3, 2, 2],
       [3, 5, 2, 0],
       [5, 1, 2, 2],
       [2, 2, 2, 5]])

In [15]:
mat - np.abs(mat) # podemos usar el signo de la operación o la función universal

array([[  0,   0,  -4,   0],
       [ -6, -10,   0,   0],
       [-10,  -2,  -4,  -4],
       [  0,   0,   0, -10]])

#### Las siguientes funciones tienen función universal correspondiente
```python
'(+, -, *, /, //, %, divmod(), ** or pow, <<, >>, &, ^, |, ~)'
```
Estas tambien
```python
'(==, <, >, <=, >=, !=)'
```


In [16]:
vet * vet

array([[1, 4, 1, 4]])

In [17]:
np.multiply(vet, vet)

array([[1, 4, 1, 4]])

### Utilizando las funciones universales de Numpy tenemos mas opciones

In [18]:
np.negative(vet) # cambia el signo a cada elemento

array([[-1,  2,  1, -2]])

In [19]:
vet

array([[ 1, -2, -1,  2]])

In [21]:
np.power(vet, vet/10)

C:\Users\hernveor\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in power
  """Entry point for launching an IPython kernel.


array([[1.        ,        nan,        nan, 1.14869835]])

In [22]:
np.exp(vet)

array([[2.71828183, 0.13533528, 0.36787944, 7.3890561 ]])

#### Ejemplos entre matrices y vectores

In [23]:
mat

array([[ 2,  3, -2,  2],
       [-3, -5,  2,  0],
       [-5, -1, -2, -2],
       [ 2,  2,  2, -5]])

In [24]:
vet

array([[ 1, -2, -1,  2]])

In [26]:
np.add(mat, vet)

array([[ 3,  1, -3,  4],
       [-2, -7,  1,  2],
       [-4, -3, -3,  0],
       [ 3,  0,  1, -3]])

In [28]:
np.add(mat, vet.reshape(4,1))

array([[ 3,  4, -1,  3],
       [-5, -7,  0, -2],
       [-6, -2, -3, -3],
       [ 4,  4,  4, -3]])

In [29]:
np.subtract(mat, vet)

array([[ 1,  5, -1,  0],
       [-4, -3,  3, -2],
       [-6,  1, -1, -4],
       [ 1,  4,  3, -7]])

In [31]:
np.subtract(mat, vet.reshape(4,1))

array([[ 1,  2, -3,  1],
       [-1, -3,  4,  2],
       [-4,  0, -1, -1],
       [ 0,  0,  0, -7]])

## Funciones Universales: Trigonométricas

In [33]:
vec = np.linspace(0, np.pi*2)
vec = np.random.choice(vec, 4)
vec

array([2.94925025, 1.02582617, 6.15495704, 4.61621778])

In [35]:
np.sin(vec)

array([ 0.19115863,  0.85514276, -0.12787716, -0.99537911])

In [36]:
np.rad2deg(vec)

array([168.97959184,  58.7755102 , 352.65306122, 264.48979592])

In [37]:
np.tan(vec)

array([-0.19474998,  1.6496046 , -0.12893572, 10.3660461 ])