In [1]:
import numpy as np

## Vector Ortogonal

- Dos vectores son ortogonales si el producto escalar entre ellos es igual a cero
- u * v = 0

In [2]:
mat = np.random.randint(-5, 5, (4, 4))
vec = np.random.randint(-5, 5, (1, 4))
mat, vec

(array([[-1, -3,  0, -1],
        [-1,  2, -4, -3],
        [ 3, -3, -2, -5],
        [ 2, -1,  0,  2]]), array([[-5,  4, -3, -1]]))

In [4]:
(np.array([1,0,3]) * np.array([0,4,0])).sum()

0

In [8]:
# Usando la función universal
np.dot(np.array([1,0,3]), np.array([0,4,0]))

0

In [10]:
# Verificando las filas, numguma fila de la matriz es ortogonal al vector
(mat * vec).sum(axis=1)

array([ -6,  28, -16, -16])

In [11]:
#vericano por columnas
(mat * vec.reshape(4,1)).sum(axis=0) # es necesario cambiar las dimenciones

array([-10,  33, -10,   6])

In [15]:
np.dot(mat, vec) # error, ya que no son identicas, debemos usar el reshape

ValueError: shapes (4,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)

In [16]:
np.dot(mat, vec.reshape(4,1))

array([[ -6],
       [ 28],
       [-16],
       [-16]])

In [17]:
np.dot(mat, vec.T)

array([[ -6],
       [ 28],
       [-16],
       [-16]])