In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from 'C:\\Users\\hernveor\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [4]:
arr1 = np.random.randint(0, 10, size=(5,5))
arr1

array([[5, 4, 9, 7, 4],
       [0, 7, 5, 2, 5],
       [0, 1, 5, 0, 0],
       [6, 0, 7, 9, 7],
       [7, 9, 5, 7, 0]])

In [5]:
# Seleccionar elementos individuales
arr1[0][2]

9

In [6]:
# tambien podemos 
arr1[0, 2]

9

In [7]:
arr1[2,2]

5

In [9]:
# Seleccionar solo una columna
arr1[:,0]

array([5, 0, 0, 6, 7])

In [10]:
# Seleccionar solo una columna
arr1[:,1]

array([4, 7, 1, 0, 9])

In [13]:
# Seleccionar solo una fila
arr1[0,:]

array([5, 4, 9, 7, 4])

In [15]:
#Seleccionar dos filas
arr1[0:2,:]

array([[5, 4, 9, 7, 4],
       [0, 7, 5, 2, 5]])

In [17]:
# Seleccionar dos columnas
arr1[:, 0:2]

array([[5, 4],
       [0, 7],
       [0, 1],
       [6, 0],
       [7, 9]])

In [20]:
# Seleccionar la submatrix de 3*3 inferior derecha
arr1[2:5, 2:5]

array([[5, 0, 0],
       [7, 9, 7],
       [5, 7, 0]])

In [21]:
# toda la matriz
arr1[:, :]

array([[5, 4, 9, 7, 4],
       [0, 7, 5, 2, 5],
       [0, 1, 5, 0, 0],
       [6, 0, 7, 9, 7],
       [7, 9, 5, 7, 0]])

In [19]:
arr1

array([[5, 4, 9, 7, 4],
       [0, 7, 5, 2, 5],
       [0, 1, 5, 0, 0],
       [6, 0, 7, 9, 7],
       [7, 9, 5, 7, 0]])