In [76]:
import numpy as np
arr = np.random.randint(0, 10, (50))
arr

array([8, 4, 0, 3, 9, 1, 0, 7, 4, 2, 9, 8, 0, 5, 8, 1, 1, 8, 5, 3, 4, 9,
       8, 0, 4, 9, 3, 3, 2, 4, 5, 4, 2, 0, 0, 8, 1, 8, 0, 6, 1, 1, 1, 0,
       1, 2, 8, 6, 5, 8])

## Para llamar los metodos, se debe usar ()

np.min(), np.max

In [81]:
arr.min()

0

In [82]:
arr.max()

9

### np.argmin, np.arrmax
Posición del valor minimo y maximo respectivamente

In [83]:
arr.argmin()

2

In [84]:
arr.argmax()

4

### np.mean()
Promedio

In [85]:
arr.mean()

3.98

### np.std()
Desviación estandar

In [86]:
arr.std()

3.1144180836875446

### np.cumsum(), np.cumprod
Suma y producto acumulativo de cada elemento

In [87]:
arr

array([8, 4, 0, 3, 9, 1, 0, 7, 4, 2, 9, 8, 0, 5, 8, 1, 1, 8, 5, 3, 4, 9,
       8, 0, 4, 9, 3, 3, 2, 4, 5, 4, 2, 0, 0, 8, 1, 8, 0, 6, 1, 1, 1, 0,
       1, 2, 8, 6, 5, 8])

In [88]:
arr.cumsum()

array([  8,  12,  12,  15,  24,  25,  25,  32,  36,  38,  47,  55,  55,
        60,  68,  69,  70,  78,  83,  86,  90,  99, 107, 107, 111, 120,
       123, 126, 128, 132, 137, 141, 143, 143, 143, 151, 152, 160, 160,
       166, 167, 168, 169, 169, 170, 172, 180, 186, 191, 199], dtype=int32)

In [89]:
arr.cumprod()

array([ 8, 32,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)

### np.prod(), np.sum()
Suma y producto

In [90]:
arr.prod()

0

In [91]:
arr.sum()

199

## Redondeo

In [92]:
arr / 17 # divido por 17 cada elemto

array([0.47058824, 0.23529412, 0.        , 0.17647059, 0.52941176,
       0.05882353, 0.        , 0.41176471, 0.23529412, 0.11764706,
       0.52941176, 0.47058824, 0.        , 0.29411765, 0.47058824,
       0.05882353, 0.05882353, 0.47058824, 0.29411765, 0.17647059,
       0.23529412, 0.52941176, 0.47058824, 0.        , 0.23529412,
       0.52941176, 0.17647059, 0.17647059, 0.11764706, 0.23529412,
       0.29411765, 0.23529412, 0.11764706, 0.        , 0.        ,
       0.47058824, 0.05882353, 0.47058824, 0.        , 0.35294118,
       0.05882353, 0.05882353, 0.05882353, 0.        , 0.05882353,
       0.11764706, 0.47058824, 0.35294118, 0.29411765, 0.47058824])

In [93]:
(arr/ 17).round(2) #Divido por 17 cada elemento y lo redondeo a 2 decimales

array([0.47, 0.24, 0.  , 0.18, 0.53, 0.06, 0.  , 0.41, 0.24, 0.12, 0.53,
       0.47, 0.  , 0.29, 0.47, 0.06, 0.06, 0.47, 0.29, 0.18, 0.24, 0.53,
       0.47, 0.  , 0.24, 0.53, 0.18, 0.18, 0.12, 0.24, 0.29, 0.24, 0.12,
       0.  , 0.  , 0.47, 0.06, 0.47, 0.  , 0.35, 0.06, 0.06, 0.06, 0.  ,
       0.06, 0.12, 0.47, 0.35, 0.29, 0.47])

### np.reshape()
Cambia las dimensiones

In [98]:
arr

array([8, 4, 0, 3, 9, 1, 0, 7, 4, 2, 9, 8, 0, 5, 8, 1, 1, 8, 5, 3, 4, 9,
       8, 0, 4, 9, 3, 3, 2, 4, 5, 4, 2, 0, 0, 8, 1, 8, 0, 6, 1, 1, 1, 0,
       1, 2, 8, 6, 5, 8])

In [99]:
arr.reshape(5, 10)

array([[8, 4, 0, 3, 9, 1, 0, 7, 4, 2],
       [9, 8, 0, 5, 8, 1, 1, 8, 5, 3],
       [4, 9, 8, 0, 4, 9, 3, 3, 2, 4],
       [5, 4, 2, 0, 0, 8, 1, 8, 0, 6],
       [1, 1, 1, 0, 1, 2, 8, 6, 5, 8]])

In [100]:
arr

array([8, 4, 0, 3, 9, 1, 0, 7, 4, 2, 9, 8, 0, 5, 8, 1, 1, 8, 5, 3, 4, 9,
       8, 0, 4, 9, 3, 3, 2, 4, 5, 4, 2, 0, 0, 8, 1, 8, 0, 6, 1, 1, 1, 0,
       1, 2, 8, 6, 5, 8])

In [106]:
arr.reshape((5, 10)).shape

(5, 10)

### np.sort
Ordena la matriz, los cambios los hace sobre la misma matriz, la sobreescribe

In [112]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 7, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 9, 9, 9, 9])

np.sort() es in-place, singinica que altera la matriz original
si deseo conservar la primer matriz con su orden, debo crear una copia de esta primero

In [117]:
arr = np.random.randint(0, 10, (50))
arr2 = arr.copy()
arr2.sort()

In [119]:
arr

array([0, 7, 0, 7, 6, 5, 1, 3, 0, 7, 3, 3, 9, 7, 6, 1, 2, 2, 9, 9, 5, 2,
       7, 3, 9, 9, 2, 3, 3, 3, 1, 8, 0, 6, 9, 5, 6, 9, 1, 6, 5, 7, 9, 3,
       5, 1, 8, 6, 9, 5])

In [120]:
arr2

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 5,
       5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 9, 9, 9,
       9, 9, 9, 9, 9, 9])