In [2]:
import numpy as np

## Diferencia entre indexación Simple y Avanzada
- La indexación avanzada crea nuevos objetos, recomendado usar
- La indexación simple devuelve una vista del objeto, una referencia

### Indexación Simple

In [3]:
arr = np.ones((3,3))*2
arr

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [4]:
arr2 = arr
arr2[0,0]= 999 # indexación simple, modifica tambien arr
arr

array([[999.,   2.,   2.],
       [  2.,   2.,   2.],
       [  2.,   2.,   2.]])

In [5]:
arr = np.arange(0,10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
vec = arr[0, :]
vec

array([0, 1, 2, 3, 4])

In [7]:
vec[0] = 999 # cambia el veector y la matriz
arr

array([[999,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

### Indexación Avanzada

In [8]:
arr2 = np.arange(0,10).reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
vec = arr2[[0,0,0,0,0],[0,1,2,3,4]] # indexación avanzada
vec

array([0, 1, 2, 3, 4])

In [10]:
vec[0] = 999
vec

array([999,   1,   2,   3,   4])

In [11]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Usando la indexación avanzada
Esta se debe usar mediante enteros de la sigueitne manera

In [12]:
arr = np.arange(0, 16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
#Seleccionar cada esquina en un nuevo objeto
arr2 = np.array([arr[0,0], arr[0,3], arr[3,0], arr[3,3]])
arr2

array([ 0,  3, 12, 15])

In [14]:
arr3 = arr[[0,0,3,3], [0,3,0,3]] # el indice se compone de un elemento en el primer parentesis y uno en el segundo
arr3

array([ 0,  3, 12, 15])

In [15]:
arr4 = arr[[0,0,3,3]] # selecciona la primera fila, luego la primera, la tercera y la tercera
arr4

array([[ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [12, 13, 14, 15]])

In [24]:
# Seleccionar las columnas
arr5 = arr[ slice(None), [0,0,3,3]] # con slice python save que necesitamos las columnas, no las filas
arr5

array([[ 0,  0,  3,  3],
       [ 4,  4,  7,  7],
       [ 8,  8, 11, 11],
       [12, 12, 15, 15]])

In [25]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
arr7 = arr[range(2), range(2)] # permite seleccionar la diagonal es ifuaal a poner [0,1], [0,1]
arr7

array([0, 5])

In [35]:
list(range(2))

[0, 1]

In [37]:
arrDiagonalPrincipal = arr[[0,1,2,3],[0,1,2,3]]
arrDiagonalPrincipal

array([ 0,  5, 10, 15])

In [38]:
arr[range(4), range(4)] #usando el range de Python

array([ 0,  5, 10, 15])

In [39]:
list(range(4))

[0, 1, 2, 3]