In [1]:
import numpy as np

In [3]:
arr = np.random.randint(0, 20, (10, 10))
arr

array([[18, 18, 10, 17,  5,  8,  8,  5, 16, 15],
       [ 1, 15,  6,  7, 15,  0,  1, 13, 18, 17],
       [17, 19, 14,  5,  6,  8, 12, 17,  2, 13],
       [12,  0,  7,  7,  0,  1, 14, 18, 10, 14],
       [19,  0, 19, 18,  9, 19, 10, 12, 10,  2],
       [13,  5,  9,  0,  1,  4, 10,  1,  9,  8],
       [13,  5, 16, 15,  3,  9,  8, 14,  8, 11],
       [ 0,  8, 10, 15,  4, 10, 19, 19,  7,  7],
       [ 5, 15, 16,  5,  8, 19,  1,  2,  7, 18],
       [16,  9,  8, 19,  4, 15, 11, 10, 13, 11]])

### 1. Calculaos el promediopor fila

In [10]:
promFila = arr.mean(axis=1, keepdims=True) # keepdims para que amntenga las dimenciones
promFila

array([[12. ],
       [ 9.3],
       [11.3],
       [ 8.3],
       [11.8],
       [ 6. ],
       [10.2],
       [ 9.9],
       [ 9.6],
       [11.6]])

In [11]:
promFila.shape

(10, 1)

### 2. Restar cada elemento del promedio

In [17]:
xiMenosProm = arr - promFila # existe una correspndencia entre el indice del arr y el del promFila, el numero de filas debe ser igual
xiMenosProm

array([[  6. ,   6. ,  -2. ,   5. ,  -7. ,  -4. ,  -4. ,  -7. ,   4. ,
          3. ],
       [ -8.3,   5.7,  -3.3,  -2.3,   5.7,  -9.3,  -8.3,   3.7,   8.7,
          7.7],
       [  5.7,   7.7,   2.7,  -6.3,  -5.3,  -3.3,   0.7,   5.7,  -9.3,
          1.7],
       [  3.7,  -8.3,  -1.3,  -1.3,  -8.3,  -7.3,   5.7,   9.7,   1.7,
          5.7],
       [  7.2, -11.8,   7.2,   6.2,  -2.8,   7.2,  -1.8,   0.2,  -1.8,
         -9.8],
       [  7. ,  -1. ,   3. ,  -6. ,  -5. ,  -2. ,   4. ,  -5. ,   3. ,
          2. ],
       [  2.8,  -5.2,   5.8,   4.8,  -7.2,  -1.2,  -2.2,   3.8,  -2.2,
          0.8],
       [ -9.9,  -1.9,   0.1,   5.1,  -5.9,   0.1,   9.1,   9.1,  -2.9,
         -2.9],
       [ -4.6,   5.4,   6.4,  -4.6,  -1.6,   9.4,  -8.6,  -7.6,  -2.6,
          8.4],
       [  4.4,  -2.6,  -3.6,   7.4,  -7.6,   3.4,  -0.6,  -1.6,   1.4,
         -0.6]])

### 3. Elevamos al cuadrado cada elemento

In [18]:
xiMenosPromCuadrado = xiMenosProm ** 2
xiMenosPromCuadrado

array([[3.6000e+01, 3.6000e+01, 4.0000e+00, 2.5000e+01, 4.9000e+01,
        1.6000e+01, 1.6000e+01, 4.9000e+01, 1.6000e+01, 9.0000e+00],
       [6.8890e+01, 3.2490e+01, 1.0890e+01, 5.2900e+00, 3.2490e+01,
        8.6490e+01, 6.8890e+01, 1.3690e+01, 7.5690e+01, 5.9290e+01],
       [3.2490e+01, 5.9290e+01, 7.2900e+00, 3.9690e+01, 2.8090e+01,
        1.0890e+01, 4.9000e-01, 3.2490e+01, 8.6490e+01, 2.8900e+00],
       [1.3690e+01, 6.8890e+01, 1.6900e+00, 1.6900e+00, 6.8890e+01,
        5.3290e+01, 3.2490e+01, 9.4090e+01, 2.8900e+00, 3.2490e+01],
       [5.1840e+01, 1.3924e+02, 5.1840e+01, 3.8440e+01, 7.8400e+00,
        5.1840e+01, 3.2400e+00, 4.0000e-02, 3.2400e+00, 9.6040e+01],
       [4.9000e+01, 1.0000e+00, 9.0000e+00, 3.6000e+01, 2.5000e+01,
        4.0000e+00, 1.6000e+01, 2.5000e+01, 9.0000e+00, 4.0000e+00],
       [7.8400e+00, 2.7040e+01, 3.3640e+01, 2.3040e+01, 5.1840e+01,
        1.4400e+00, 4.8400e+00, 1.4440e+01, 4.8400e+00, 6.4000e-01],
       [9.8010e+01, 3.6100e+00, 1.0000e-0

### 4. Hacemos la sumatoria hacia la derecha

In [20]:
xiMenosPromCuadradoSuma = xiMenosPromCuadrado.sum(axis=1, keepdims=True)
xiMenosPromCuadradoSuma

array([[256. ],
       [454.1],
       [300.1],
       [370.1],
       [443.6],
       [178. ],
       [169.6],
       [344.9],
       [412.4],
       [168.4]])

### 5. Dividimos entre n-1

In [30]:
xiMenosPromCuadradoSumaEntreN1 = xiMenosPromCuadradoSuma / (xiMenosPromCuadradoSuma.size)
xiMenosPromCuadradoSumaEntreN1

array([[25.6 ],
       [45.41],
       [30.01],
       [37.01],
       [44.36],
       [17.8 ],
       [16.96],
       [34.49],
       [41.24],
       [16.84]])

### 6. Aplicar la raiz cuadrada

In [31]:
xiMenosPromCuadradoSumaEntreN1Raiz = xiMenosPromCuadradoSumaEntreN1 ** 0.5
xiMenosPromCuadradoSumaEntreN1Raiz # desviación estandar para cada fila

array([[5.05964426],
       [6.73869424],
       [5.47813837],
       [6.08358447],
       [6.66033032],
       [4.21900462],
       [4.11825206],
       [5.87281874],
       [6.42183774],
       [4.10365691]])

### 7. Revisar usando el metodo directo

In [33]:
arr.std(axis=1, keepdims=True)

array([[5.05964426],
       [6.73869424],
       [5.47813837],
       [6.08358447],
       [6.66033032],
       [4.21900462],
       [4.11825206],
       [5.87281874],
       [6.42183774],
       [4.10365691]])

### 8. Calculamos la desviación estandar de las columnas (hacia abajo) 

In [41]:
arr.std(axis=0).reshape(10, 1)

array([[6.62117814],
       [6.68131724],
       [4.20119031],
       [6.36867333],
       [4.12916456],
       [6.3882705 ],
       [5.18073354],
       [6.17170965],
       [4.42718872],
       [4.65188134]])