In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
arr.sum()

300

### Axis
Axis o ejes hace referencia a los ejes x y y, podemos hacer la anterior suma para una fila o columna en especial.

In [8]:
arr.sum(axis=0) # suma de cada una de las columnas

array([50, 55, 60, 65, 70])

In [11]:
arr.sum(axis=1) # suma de las filas o hacia la derecha

array([ 10,  35,  60,  85, 110])