Seleccionar todos los datos de una matriz 10x10 excepto las filas y columnas de los bordes

In [11]:
import numpy as np
arr = np.random.randint(0, 10, size=(10,10))

In [12]:
arr

array([[4, 1, 2, 8, 3, 3, 7, 7, 6, 3],
       [9, 1, 3, 0, 8, 4, 1, 8, 4, 4],
       [0, 5, 6, 7, 1, 0, 0, 3, 4, 0],
       [2, 6, 4, 3, 0, 6, 1, 6, 1, 6],
       [2, 2, 5, 6, 3, 5, 1, 3, 8, 3],
       [9, 4, 5, 6, 0, 6, 0, 3, 7, 4],
       [1, 3, 7, 1, 6, 2, 8, 6, 1, 2],
       [1, 5, 3, 6, 1, 6, 8, 6, 2, 3],
       [5, 2, 3, 3, 3, 4, 9, 2, 9, 7],
       [0, 0, 1, 4, 1, 0, 4, 3, 3, 7]])

In [13]:
arr[1:9, 1:9]

array([[1, 3, 0, 8, 4, 1, 8, 4],
       [5, 6, 7, 1, 0, 0, 3, 4],
       [6, 4, 3, 0, 6, 1, 6, 1],
       [2, 5, 6, 3, 5, 1, 3, 8],
       [4, 5, 6, 0, 6, 0, 3, 7],
       [3, 7, 1, 6, 2, 8, 6, 1],
       [5, 3, 6, 1, 6, 8, 6, 2],
       [2, 3, 3, 3, 4, 9, 2, 9]])

In [14]:
# Usando indexación negativa
arr[1:-1, 1:-1]

array([[1, 3, 0, 8, 4, 1, 8, 4],
       [5, 6, 7, 1, 0, 0, 3, 4],
       [6, 4, 3, 0, 6, 1, 6, 1],
       [2, 5, 6, 3, 5, 1, 3, 8],
       [4, 5, 6, 0, 6, 0, 3, 7],
       [3, 7, 1, 6, 2, 8, 6, 1],
       [5, 3, 6, 1, 6, 8, 6, 2],
       [2, 3, 3, 3, 4, 9, 2, 9]])