In [3]:
import numpy as np

## Métodos de Funciones Universales (Avanzado): reduce() y accumulate()

In [5]:
mat = np.ones((5,5))
mat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### accumulate
Las funciones como np.add(), np,subtract(), solo reciben dos argumentos, si ncesito operar con un numero mayor de argumentos, debo usar accumulate

In [7]:
np.add.accumulate([mat, mat])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [8]:
mat + mat

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [9]:
np.add(mat, mat)

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [10]:
np.add.accumulate([mat, mat, mat, mat])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]]])

In [11]:
mat = np.ones((3,3))*2
mat

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [12]:
np.add.accumulate([mat, mat, mat])

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

In [14]:
np.subtract.accumulate([mat, mat, mat])

array([[[ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[-2., -2., -2.],
        [-2., -2., -2.],
        [-2., -2., -2.]]])

### reduce
Funciona igual que accumulate, pero solo muestra el resultado final

In [16]:
np.subtract.reduce([mat, mat, mat])

array([[-2., -2., -2.],
       [-2., -2., -2.],
       [-2., -2., -2.]])

In [17]:
np.multiply.accumulate([mat, mat, mat])

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]]])

In [18]:
np.multiply.reduce([mat, mat, mat])

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])