In [28]:
import numpy as np

### La igualación es un paso por referencia

In [29]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [30]:
arr2 = arr1
arr2

array([1, 2, 3, 4, 5])

In [31]:
arr2[2]=999
arr2

array([  1,   2, 999,   4,   5])

In [32]:
arr1 #cambia el valor en el arr1

array([  1,   2, 999,   4,   5])

### np.copy()

In [33]:
arr3 = np.array([1, 2, 3, 4, 5])
arr3

array([1, 2, 3, 4, 5])

In [34]:
arr4 = arr3.copy()
arr4

array([1, 2, 3, 4, 5])

In [35]:
arr4[2] = 9999
arr4

array([   1,    2, 9999,    4,    5])

In [36]:
arr3

array([1, 2, 3, 4, 5])

### np.rechape() whtih order

In [37]:
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr5.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [39]:
arr5.reshape((5,2), order="F")

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### tolist(), tostring()
Convertir en una lista de Python

In [40]:
arr5.tolist() # ya o tiene los metodos y atributos de numpy

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
print(type(arr5))
print(type(arr5.tolist()))

<class 'numpy.ndarray'>
<class 'list'>


In [42]:
arr5.tostring() # representación en byts

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00'

### Cambiar el tipo de dato, por alguno de los 24 tipos que soporte numpy

In [43]:
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr5.dtype

dtype('int32')

In [46]:
arr5.astype('float')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
arr5.astype('float').dtype

dtype('float64')

### LLevar a un archivo
````python
tofile()
```

In [51]:
arr5.tofile('matriz-con-Numpy.txt', sep=',')

In [57]:
arr6 = np.arange(10000).reshape(100,100)
arr6.tofile('matriz100x100.txt', sep=';')

In [58]:
arr6

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

### Guardar la matriz en codigo binario, serializado, especial para transportar
```python
np.dump()
```

In [59]:
arr6.dump('matriz100x100dump.txt')